<?php
/**
 * Created by PhpStorm.
 * User: mesqu
 * Date: 20/10/2017
 * Time: 17:33
 */

/***************************************************************************/
//SELECT AND SHOW THE CONTENT OF A TABLE OF THE DB - USING A FUNCTION CREATED BY ME
/***************************************************************************/

/**************/
//USERS
/*************/

/*try{
    $sql = new Sql();
    $sql->mySelect("SELECT * FROM user");

}
catch(Exception $e){

    Echo $e->getMessage();

}finally{

    Echo "User Table Shown";

}*/

/**************/
//CUSTOMERS
/*************/

/*try{

    $sql->mySelect("SELECT * FROM customer");
}
catch(Exception $e){

    echo $e->getMessage();

}finally{

    Echo "Costumer Table Shown";

}*/

/**************/
//MOVIE
/*************/

/*try{
    $sql->mySelect("SELECT * FROM movie");

}catch(Exception $e){

    echo $e->getMessage();


}finally{

    echo "Movie Table Shown";
}*/



//erros->As exceptions não estão a funcionar quando mudo por exemplo para um ID que não existe na tabela